model:

  checkpoint: # checkpoint path
  


sample:
  seed: 2021
  num_samples: 2000
  num_steps: 1000
  pos_only: False
  center_pos_mode: protein
  sample_num_atoms: prior_ref
  frag: Frag # NoFrag
