model:

  checkpoint: /home/csy/work/3D/PharDiff/logs_diffusion/training_2023_11_06__16_04_28NoFrag/checkpoints/27200.pt
  
  ## Most highest performance checkpoint [PINN]
  #checkpoint: /home/csy/work/3D/targetdiff_PINN/logs_diffusion/training_2023_09_30__19_56_28/checkpoints/30600.pt


sample:
  seed: 2021
  num_samples: 10
  num_steps: 1000
  pos_only: False
  center_pos_mode: protein
  sample_num_atoms: prior_ref
  frag: NoFrag
